In [1]:
import numpy as np

In [2]:
#crear un arreglo 
#(como es un método le pasaremos los arreglos a través de un corchete)

np.array([10, 20, 24, 5, 15, 50])

array([10, 20, 24,  5, 15, 50])

In [3]:
#el arreglo comienza a partir de la posición 0.
#llamo al arreglo de la posición 4.

a = np.array([10, 30, 4, 30, 51, 7, 2, 4, 40, 100])
a[4]

51

In [4]:
#mostraremos los datos del arrego a partir del indice 3.

a[3:]

array([ 30,  51,   7,   2,   4,  40, 100])

In [5]:
#mostraremos los datos a partir de intervalos. del indice 3 al 7.

a[3:7]

array([30, 51,  7,  2])

In [6]:
#mostraremos los datos cada 4 espacios.

a[0::4]

array([10, 51, 40])

In [7]:
#creamos arreglos de manera dinámica con diferentes funciones.
#zeros: como es un metodo necesita llevar parentesis.

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
#arreglo de dos dimensiones, abrimos dos parentesis porque lleva dos parámetros
# 4: filas, 5: columnas

ones = np.ones((4,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
#para saber qué tipo de arreglo es: arreglo de n dimensiones

type(ones)

numpy.ndarray

In [10]:
#linespace: para generar datos y crear gráficos
#crea elementos entre 3 y 10, y tiene 5 elementos

np.linspace(3, 10, 5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [11]:
#crear un arreglo de dos dimensiones

b = np.array([['x', 'y', 'z'], ['a', 'c', 'e']])
print(b)
type(b)

[['x' 'y' 'z']
 ['a' 'c' 'e']]


numpy.ndarray

In [12]:
#para saber cuantas dimensiones tiene: nos dice que tiene 2 dimensiones

b.ndim

2

In [13]:
#el método sort nos ordena de menor a mayor

c = [12, 4, 10, 40, 2]
np.sort(c)

array([ 2,  4, 10, 12, 40])

In [14]:
#nuestro arreglo está ordenado a través de edad (menor a mayor)

cabeceras = [ ('nombre', 'S10'), ('edad', int) ]
datos = [ ('Juan', 10), ('Maria', 70), ('Javier', 42), ('Samuel', 15)]
usuarios = np.array(datos, dtype = cabeceras)

np.sort(usuarios, order = 'edad')

array([(b'Juan', 10), (b'Samuel', 15), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i4')])

In [15]:
#mediante arange generamos elementos dinámicos de un arreglo.

np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
#con intervalo

np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
#incrementamos cada 3

np.arange(5, 50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [18]:
#crear arreglo bidimensional con el método full
# 3 filas, 5 columnas, que contenta unicamente un valor: 10

np.full((3, 5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [19]:
#crear una diagonal en un arreglo bidimensional

np.diag([0, 3, 9, 10, 42])

array([[ 0,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0],
       [ 0,  0,  9,  0,  0],
       [ 0,  0,  0, 10,  0],
       [ 0,  0,  0,  0, 42]])